
function manyDataPoints() {


  let arr = []
  let counter = 0;
  let time = new Date("2025-06-02T01:10:10");

  for (let i = 0; i < 10; i++) {
    arr.push({
      reading_time: new Date(time),
      energy_usage: counter,
      light_status: "OFF",
      brightness_level: 60,
      power_consumption: 40,
      battery_status: 85,
      sensor_health: "Good",
      location: "Langara 49th Station",
    });

    counter++;
    time.setMinutes(time.getMinutes() + 30);
  }

  return arr;
}

export let testData = manyDataPoints();

// export let testData = [
//   // 1 year ago (Mar 20, 2024)
//   {
//     reading_time: new Date("2024-03-20T01:10:10"),
//     energy_usage: 150,
//     light_status: "OFF",
//     brightness_level: 60,
//     power_consumption: 40,
//     battery_status: 85,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2024-03-20T03:20:10"),
//     energy_usage: 300,
//     light_status: "ON",
//     brightness_level: 80,
//     power_consumption: 100,
//     battery_status: 75,
//     sensor_health: "Warning",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2024-03-20T05:40:10"),
//     energy_usage: 250,
//     light_status: "ON",
//     brightness_level: 75,
//     power_consumption: 80,
//     battery_status: 65,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2024-03-20T07:15:10"),
//     energy_usage: 200,
//     light_status: "OFF",
//     brightness_level: 70,
//     power_consumption: 60,
//     battery_status: 70,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2024-03-20T09:25:10"),
//     energy_usage: 175,
//     light_status: "ON",
//     brightness_level: 85,
//     power_consumption: 50,
//     battery_status: 80,
//     sensor_health: "Warning",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2024-03-20T11:10:10"),
//     energy_usage: 125,
//     light_status: "OFF",
//     brightness_level: 60,
//     power_consumption: 35,
//     battery_status: 90,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2024-03-20T13:10:10"),
//     energy_usage: 280,
//     light_status: "ON",
//     brightness_level: 90,
//     power_consumption: 75,
//     battery_status: 85,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2024-03-20T15:50:10"),
//     energy_usage: 320,
//     light_status: "ON",
//     brightness_level: 95,
//     power_consumption: 95,
//     battery_status: 70,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2024-03-20T18:10:10"),
//     energy_usage: 375,
//     light_status: "ON",
//     brightness_level: 85,
//     power_consumption: 110,
//     battery_status: 60,
//     sensor_health: "Warning",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2024-03-20T20:30:10"),
//     energy_usage: 400,
//     light_status: "ON",
//     brightness_level: 100,
//     power_consumption: 120,
//     battery_status: 50,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },

//   // Year-to-date (Jan 1, 2025 - Mar 2, 2025)
//   {
//     reading_time: new Date("2025-01-01T01:30:10"),
//     energy_usage: 180,
//     light_status: "ON",
//     brightness_level: 70,
//     power_consumption: 50,
//     battery_status: 90,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2025-01-07T02:10:10"),
//     energy_usage: 220,
//     light_status: "ON",
//     brightness_level: 85,
//     power_consumption: 55,
//     battery_status: 80,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2025-01-15T12:45:10"),
//     energy_usage: 300,
//     light_status: "OFF",
//     brightness_level: 90,
//     power_consumption: 75,
//     battery_status: 75,
//     sensor_health: "Warning",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2025-01-21T13:55:10"),
//     energy_usage: 250,
//     light_status: "ON",
//     brightness_level: 70,
//     power_consumption: 80,
//     battery_status: 65,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2025-01-28T14:20:10"),
//     energy_usage: 280,
//     light_status: "ON",
//     brightness_level: 80,
//     power_consumption: 60,
//     battery_status: 85,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2025-02-01T06:30:10"),
//     energy_usage: 340,
//     light_status: "OFF",
//     brightness_level: 60,
//     power_consumption: 90,
//     battery_status: 55,
//     sensor_health: "Warning",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2025-02-05T09:40:10"),
//     energy_usage: 190,
//     light_status: "ON",
//     brightness_level: 75,
//     power_consumption: 50,
//     battery_status: 95,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2025-02-08T11:50:10"),
//     energy_usage: 350,
//     light_status: "ON",
//     brightness_level: 80,
//     power_consumption: 70,
//     battery_status: 70,
//     sensor_health: "Warning",
//     location: "Langara 49th Station",
//   },

//   // Today (Mar 2, 2025)
//   {
//     reading_time: new Date("2025-03-02T01:10:10"),
//     energy_usage: 175,
//     light_status: "OFF",
//     brightness_level: 65,
//     power_consumption: 45,
//     battery_status: 85,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2025-03-02T03:30:10"),
//     energy_usage: 225,
//     light_status: "ON",
//     brightness_level: 75,
//     power_consumption: 60,
//     battery_status: 80,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2025-03-02T05:50:10"),
//     energy_usage: 310,
//     light_status: "ON",
//     brightness_level: 85,
//     power_consumption: 90,
//     battery_status: 70,
//     sensor_health: "Warning",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2025-03-02T08:10:10"),
//     energy_usage: 200,
//     light_status: "OFF",
//     brightness_level: 65,
//     power_consumption: 70,
//     battery_status: 85,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2025-03-02T10:20:10"),
//     energy_usage: 280,
//     light_status: "ON",
//     brightness_level: 90,
//     power_consumption: 75,
//     battery_status: 65,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2025-03-02T12:30:10"),
//     energy_usage: 320,
//     light_status: "ON",
//     brightness_level: 85,
//     power_consumption: 85,
//     battery_status: 70,
//     sensor_health: "Warning",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2025-03-02T15:00:10"),
//     energy_usage: 190,
//     light_status: "ON",
//     brightness_level: 70,
//     power_consumption: 55,
//     battery_status: 75,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2025-03-02T17:30:10"),
//     energy_usage: 250,
//     light_status: "ON",
//     brightness_level: 80,
//     power_consumption: 130,
//     battery_status: 60,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2025-05-07T19:10:10"),
//     energy_usage: 800,
//     light_status: "ON",
//     brightness_level: 90,
//     power_consumption: 800,
//     battery_status: 50,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
//   {
//     reading_time: new Date("2025-05-07T19:15:10"),
//     energy_usage: 800,
//     light_status: "ON",
//     brightness_level: 90,
//     power_consumption: 800,
//     battery_status: 50,
//     sensor_health: "Good",
//     location: "Langara 49th Station",
//   },
// ];
